"""empty message

Revision ID: fd3c57fe4c68
Revises: 
Create Date: 2023-04-01 18:28:51.521893

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.schema import Sequence, CreateSequence

# revision identifiers, used by Alembic.
revision = 'fd3c57fe4c68'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    
    op.execute(CreateSequence(Sequence('makers_id_seq')))
    op.execute(CreateSequence(Sequence('sales_id_seq')))
    op.execute(CreateSequence(Sequence('styles_id_seq')))
    op.execute(CreateSequence(Sequence('vendors_id_seq')))
    op.execute(CreateSequence(Sequence('tags_id_seq')))
    op.execute(CreateSequence(Sequence('entries_id_seq')))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('makers',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('makers_id_seq')"), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ka_id', sa.String(length=12), nullable=False),
    sa.Column('ka_name', sa.String(length=100), nullable=False),
    sa.Column('display', sa.String(length=100), nullable=False),
    sa.Column('instagram', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('sales',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('sales_id_seq')"), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('display', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('styles',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('styles_id_seq')"), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('display', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('vendors_id_seq')"), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display', sa.String(length=100), nullable=False),
    sa.Column('website', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('entries',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('entries_id_seq')"), nullable=False),
    sa.Column('maker_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('colorway', sa.String(length=100), nullable=False),
    sa.Column('sculpt_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('clw_num', sa.Integer(), nullable=False),
    sa.Column('clw_total', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('adjustment', sa.Float(), nullable=False),
    sa.Column('retail', sa.Float(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('sale_post', sa.String(length=500), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('received', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('epoch', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('sold_date', sa.Date(), nullable=False),
    sa.Column('is_sold', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('will_sell', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('count_include', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('sculpt_style_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['maker_id'], ['makers.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.ForeignKeyConstraint(['sculpt_style_id'], ['styles.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('tags_id_seq')"), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    op.drop_table('entries')
    op.drop_table('vendors')
    op.drop_table('styles')
    op.drop_table('sales')
    op.drop_table('makers')
    # ### end Alembic commands ###
